import { storyURLs } from '../../constants';

export type Type = 'all' | 'design' | 'development';

export interface Project {
  title: string;
  subtitle: string;
  headerIconSrc: string;
  headerIconAlt: string;
  contentText: string;
  buttonText: string;
  projectSubURL: string;
  bottomText: string;
  bottomIconSrc: string;
  bottomIconAlt: string;
  types: Type[];
  tags: string[];
  backgroundStyling: string;
}

export const ProjectsArray: Project[] = [
  {
    title: 'D-Planner, LLC',
    subtitle: 'Entrepreneurship',
    headerIconSrc: './search.svg',
    headerIconAlt: 'D-Planner logo',
    contentText: 'Academic planning is difficult for students, especially when information is fragmented and hard to find. D-Planner is a better way of planning out your time at college. Winner of the 2018 DALI Pitch Competition.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.dplanner,
    bottomText: 'Co-founder, Project Designer, Developer',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development', 'design'],
    tags: ['javascript', 'python', 'html', 'css', 'sass', 'mern', 'mongo', 'express', 'node', 'react', 'redux', 'entrepreneurship', 'dartmouth', 'planning', 'academic', 'dali'],
    backgroundStyling: 'radial-gradient(108.61% 108.61% at 50% 50%, rgba(34, 34, 34, 0) 42.89%, rgba(34, 34, 34, 0.3) 94.11%), radial-gradient(107.22% 107.22% at 50% 50%, rgba(81, 143, 245, 0.6) 0%, rgba(81, 143, 245, 0) 100%), #5E51F1',
  },
  {
    title: 'Intermediate Computer Interface',
    subtitle: 'US Patent and Trademark Office',
    headerIconSrc: './chip.svg',
    headerIconAlt: 'Computer chip',
    contentText: 'During a high school independent study course I created and patented a hardware-accelerated HID macro device which is able to spoof or amplify incoming USB signals. The device is functional on any valid USB port.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.icid,
    bottomText: 'US Patent 9,632,952',
    bottomIconSrc: '',
    bottomIconAlt: 'USPTO logo',
    types: ['development'],
    tags: ['c', 'c++', 'arduino', 'usb', 'embedded', 'patent', 'macro', 'hardware'],
    backgroundStyling: 'radial-gradient(89.62% 89.62% at 50% 50%, rgba(34, 34, 34, 0) 53.17%, rgba(34, 34, 34, 0.6) 100%), #344452',
  },
  {
    title: 'Mini Design Course',
    subtitle: 'DALI Lab Design Lecturer',
    headerIconSrc: './dartmouth.svg',
    headerIconAlt: 'Dartmouth College logo',
    contentText: 'I designed and taught a 10-week beginner design course for 60 aspiring design students at Dartmouth College. The course was taught in two sections, one for basics and one for advanced topics in HCD.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.mdc,
    bottomText: 'Senior Design Lecturer',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['design'],
    tags: ['hcd', 'human', 'research', 'user', 'dali'],
    backgroundStyling: 'radial-gradient(95.95% 95.95% at 50% 50%, rgba(85, 85, 85, 0) 0%, rgba(85, 85, 85, 0) 58.02%, rgba(85, 85, 85, 0.3) 100%), #38B2AB',
  },
  {
    title: 'Term Scheduling Portal',
    subtitle: 'Registrar, Dartmouth College',
    headerIconSrc: './dartmouth.svg',
    headerIconAlt: 'Dartmouth College logo',
    contentText: 'Dartmouth College’s existing term election interface has a success rate of 25%, and does not support international students. How might Dartmouth make sure their interface works for everyone?',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.scheduling,
    bottomText: 'Designer, Developer, Development Mentor',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['design', 'development'],
    tags: ['dali', 'dartmouth', 'javascript', 'html', 'css', 'sass', 'mern', 'mongo', 'express', 'react', 'redux', 'node', 'scheduling', 'academic', 'planning'],
    backgroundStyling: 'radial-gradient(88.48% 88.48% at 50% 50%, rgba(34, 34, 34, 0) 39.13%, rgba(34, 34, 34, 0.4) 100%), rgba(27, 74, 35, 0.9)',
  },
  {
    title: 'JestJS UI Testing Workshop',
    subtitle: 'DALI Lab Development Lecturer',
    headerIconSrc: './react.svg',
    headerIconAlt: 'ReactJS logo',
    contentText: 'After noticing higher than normal rates of bug-related crashes in my software lab\'s ReactJS and NodeJS apps, I wrote and delivered a workshop introducing developers to unit testing with the JestJS javascript testing framework.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.jest,
    bottomText: 'Developer, Development Mentor',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development'],
    tags: ['unit', 'testing', 'jest', 'dali', 'ui', 'react', 'redux', 'html', 'css', 'sass', 'typescript'],
    backgroundStyling: 'radial-gradient(106.2% 106.2% at 50% 50%, rgba(255, 255, 255, 0.15) 13.09%, rgba(255, 255, 255, 0.103379) 50.52%, rgba(255, 255, 255, 0) 100%), #171E27',
  },
  {
    title: 'Portable Radio Repeater',
    subtitle: 'Dartmouth College',
    headerIconSrc: './dartmouth.svg',
    headerIconAlt: 'Dartmouth College logo',
    contentText: 'A highly portable radio repeater mast that allows search and rescue workers to communicate via radio in highly mountainous and dangerous terrain, built to support and improve existing radio infrastructure.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.repeater,
    bottomText: 'Developer, Electrical Systems Manager',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development'],
    tags: ['dartmouth', 'rescue', 'repeater', 'hanover', 'c', 'c++', 'arduino', 'network', 'radio', 'uhf', 'vhf'],
    backgroundStyling: 'radial-gradient(93.04% 93.04% at 50% 50%, rgba(26, 26, 26, 0) 16.15%, #1A1A1A 100%), rgba(48, 48, 53, 0.95)',
  },
  {
    title: 'Granite State Volunteering',
    subtitle: 'NH State Government',
    headerIconSrc: './newhampshire.svg',
    headerIconAlt: 'New Hampshire vector outline',
    contentText: 'Working with the New Hampshire state government, I led a team in developing a central respository for all volunteer opportunities in the state of New Hampshire, as well as an interface portal for admins and volunteers.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.graniteState,
    bottomText: 'Lead Developer, Development Mentor',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development'],
    tags: ['dali', 'new', 'hampshire', 'mern', 'javascript', 'html', 'css', 'sass', 'mongo', 'express', 'react', 'redux', 'node', 'govern', 'volunteer', 'mentor'],
    backgroundStyling: 'radial-gradient(89.62% 89.62% at 50% 50%, rgba(34, 34, 34, 0) 53.17%, rgba(34, 34, 34, 0.6) 100%), rgba(72, 82, 52, 0.9)',
  },
  // {
  //   title: 'ReactJS + Typescript Starter',
  //   subtitle: 'DALI Lab Development Lecturer',
  //   headerIconSrc: './typescript.svg',
  //   headerIconAlt: 'Typescript logo',
  //   contentText: 'Veritatis ipsa laborum ducimus facilis qui. Eveniet et hic quidem rem qui natus aut. Recusandae enim iure qui ab. Labore nulla cumque aliquam et. Quod fugiat et officia officiis rerum debitis vero molestias.',
  //   buttonText: 'coming soon!',
  //   projectSubURL: storyURLs.tsStarter,
  //   bottomText: 'Developer, Development Mentor',
  //   bottomIconSrc: '',
  //   bottomIconAlt: '',
  //   types: ['development'],
  //   tags: [],
  //   backgroundStyling: 'radial-gradient(107.72% 107.72% at 50% 50%, rgba(255, 255, 255, 0.15) 13.09%, rgba(255, 255, 255, 0.103379) 58.07%, rgba(255, 255, 255, 0) 100%), #171E27',
  // },
  {
    title: 'Advanced CRUD Starter',
    subtitle: 'DALI Lab Senior Developer',
    headerIconSrc: './typescript.svg',
    headerIconAlt: 'Typescript logo',
    contentText: 'Configuring a project takes a significant amount of time for new and intermediate developers, and to combat this problem I developed a two-part starter pack that saves teams upwards of 10 days of development per term.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.crudTemplate,
    bottomText: 'Senior Developer, Development Mentor',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development'],
    tags: ['crud', 'template', 'dali', 'mentor', 'dev', 'starter', 'html', 'css', 'sass', 'typescript', 'javascript', 'redux', 'mongo', 'express', 'react', 'node'],
    backgroundStyling: 'radial-gradient(107.72% 107.72% at 50% 50%, rgba(255, 255, 255, 0.15) 13.09%, rgba(255, 255, 255, 0.103379) 58.07%, rgba(255, 255, 255, 0) 100%), #171E27',
  },
  {
    title: 'Whiteboard Productivity',
    subtitle: 'DALI Lab, Dartmouth College',
    headerIconSrc: './github.svg',
    headerIconAlt: 'Github logo',
    contentText: 'An all-encompassing productivity app that empowers users to take full control over their lives through relevant, integrated planning functionality. Built in conjunction with Tuck School of Business.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.whiteboard,
    bottomText: 'Developer, Development Mentor',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['development'],
    tags: ['react', 'javascript', 'redux', 'google', 'firebase'],
    backgroundStyling: 'radial-gradient(107.09% 107.09% at 50% 50%, rgba(255, 255, 255, 0.15) 32.84%, rgba(255, 255, 255, 0) 100%), #434279',
  },
  {
    title: 'MindSquare',
    subtitle: 'Dartmouth College',
    headerIconSrc: './dartmouth.svg',
    headerIconAlt: 'Dartmouth College logo',
    contentText: 'On college campuses, fear of missing out is a powerful social motivator. MindSquare helps users reframe what it means to take personal time away from stressful daily activities through personalized digital mosaics.',
    buttonText: 'coming soon!',
    projectSubURL: storyURLs.mindsquare,
    bottomText: 'Product Designer',
    bottomIconSrc: '',
    bottomIconAlt: '',
    types: ['design'],
    tags: ['dartmouth', 'mindfulness', 'hcd'],
    backgroundStyling: 'radial-gradient(92.28% 92.28% at 50% 50%, rgba(81, 143, 245, 0) 0%, rgba(23, 74, 91, 0.5) 100%), #60A8C1',
  },
  // {
  //   title: 'TODO: Discuss this portfolio',
  //   subtitle: '',
  //   headerIconSrc: '',
  //   headerIconAlt: '',
  //   contentText: '',
  //   buttonText: '',
  //   projectSubURL: '',
  //   bottomText: '',
  //   bottomIconSrc: '',
  //   bottomIconAlt: '',
  //   tags: ['development', 'design'],
  //   tags: [],
  //   backgroundStyling: 'radial-gradient(92.28% 92.28% at 50% 50%, rgba(81, 143, 245, 0) 0%, rgba(23, 74, 91, 0.5) 100%), #60A8C1',
  // },
];
